### ISSUE TITLE
I can't go to next with custom content

### ISSUE THREAD

**Issue by wzol** [henrygd/bigger-picture#10]
Even on the demo page I can't go to next or previous content on "Video / audio / iframes" or the first too with "HTML". The same is on mobile - no next or prev buttons also swipe doesn't work. Am I missing something?

**Comment by henrygd** [comment]
You're not missing anything, I just made the choice to display them individually. You may make galleries with any content type if you wish.

**Comment by henrygd** [comment]
Just to add -- the reason why I have them open individually is because the buttons are annoying if they sit over the content.

In the future I may add an option to have the buttons hide automatically after a period of mouse / touch inactivity.

**Comment by wzol** [comment]
Would it be possible to open custom content in smaller area (90% width) - so the next and prev button would fit?

**Comment by henrygd** [comment]
HTML yes -- you control the dimensions with CSS.

**Comment by wzol** [comment]
After some testing this seems to work for styling, but can't to add the buttons yet:

```
.bp-wrap {
    display: flex;
    justify-content: center;
}

.bp-inner {
    width: calc(100% - 2 * 58px - 16px); /* place for the buttons and some margin */
}
```
