### ISSUE TITLE
With added thumbnails I can't reach thumbs which are behind screen width

### ISSUE THREAD

**Issue by wzol** [henrygd/bigger-picture#11]
On desktop I can't switch to pictures from thumbs which are out of visible area - so example here -https://codesandbox.io/s/bigger-picture-thumbnails-vpszy7 - I can't reach the last image as I don't see the thumb. You can swipe the thumbs on mobile, but no way to reach the end or the next page on desktop. Maybe it the selected thumb could position to the center? It is not perfect but a workaround.

**Comment by henrygd** [comment]
Should be able to drag. What browser are you on?

Just fyi this is not a part of the library and not supported -- just an example of extending it. So I'm going to close this issue but I will continue to respond.

**Comment by wzol** [comment]
How about a next - prev buttons for thumbs, I think I've seen that before somewhere.

**Comment by henrygd** [comment]
I don't know about buttons, but I can change the cursor to indicate that it's draggable if the thumbnails extend past the screen edge. That might be more intuitive.

But right now it's almost midnight for me and I'm on a road trip so I'm not 100% sure when I'll get to it.

**Comment by wzol** [comment]
Ok, I understand - it is morning here :) so have a nice night ;)
