### ISSUE TITLE
Custom actions like Zoom icon 

### ISSUE THREAD

**Issue by no-1ne** [henrygd/bigger-picture#17]
Hello @henrygd, Thank you for the great library. 

Coming to the question, What is the simplest way to add custom icons(and corresponding actions to invoke on click) specifically next to close icon without editing the code. 
Here is the relavent documentation for the same using photoswipe 
https://photoswipe.com/adding-ui-elements/

Thanks in advance.

**Comment by henrygd** [comment]
There's no specific method for this, but you can do it without too much trouble using the current api.

See this for a basic example in vanilla js:

https://codesandbox.io/s/bigger-picture-extra-buttons-i7mnpg

You can use the `onUpdate` method to keep track of the currently displayed item properties if you need them.

There's no way to toggle the zoom currently, if that's what you want to do, but I can probably add it in the next release.

**Comment by henrygd** [comment]
I have this in my todos. Right now the feature I'm prioritizing is the ability to open from cropped / object-fit images and figuring out the best way to do that has eaten all the time I've had for this project recently, but hopefully I can tack this on to the next release.

If it helps, there's a `bp-zoomed` class that gets added to the container (`.bp-wrap`) when the image is zoomed, so as of now you can check using `classList.contains('bp-zoomed')`.

**Comment by henrygd** [comment]
Added in 1.1.8.

I updated the codesandbox example above to have a working zoom button: https://codesandbox.io/s/bigger-picture-extra-buttons-i7mnpg

Let me know if you have any questions.

**Comment by henrygd** [comment]
The controls are hidden by default when the image is zoomed on small screens to provide more space to the image.

Try adding this to your css to prevent this behavior:

```css
.bp-zoomed.bp-small .bp-controls {
  opacity: 1;
}
.bp-zoomed.bp-small .bp-controls button {
  pointer-events: auto;
}
```
