### ISSUE TITLE
[Feature Request] add support to rotate image

### ISSUE THREAD

**Issue by Zzombiee2361** [henrygd/bigger-picture#18]
Allow rotating image (or optionally other elements) from within the lightbox. Also consider exposing the rotation state and method to allow changing rotation programmatically

**Comment by henrygd** [comment]
My view is that this feature is too niche to justify the extra weight it will add to the library, so it will not be added any time soon. 

Off the top of my head, the only lightbox that I know supports image rotation is lightGallery, so you might want to check that out. But be aware that it's not free for closed source projects.
