### ISSUE TITLE
Attempted to preload a URL that does not belong to this app ...?

### ISSUE THREAD

**Issue by germyparker** [henrygd/bigger-picture#19]
I think the problem is probably me, but I can't figure out what I'm doing wrong!

Every time I try to use a local image, I get the following error: 

```
client.js?t=1673409339167&v=0edd5263:207 Uncaught (in promise) Error: Attempted to preload a URL that does not belong to this app: http://localhost:5173/masashi-wakui/masashi-wakui-misc-10.jpeg
    at preload_data (client.js?t=1673409339167&v=0edd5263:207:10)
    at preload (client.js?t=1673409339167&v=0edd5263:1184:6)
    at client.js?t=1673409339167&v=0edd5263:1145:5
```

I made a minimal repo for it: 

https://github.com/germyparker/bigger-picture-error

Maybe worth pointing out, idk:  I also tried this with the bigger-picture-examples/sveltekit-basic repo.  The repo itself had some conflict errors, and I didn't feel like dealing with it, so I reconstructed it and downloaded all of the images, stored them locally, and the same errors occurred.

**Comment by henrygd** [comment]
This is definitely a sveltekit thing. You may be able to fix by disabling preload for those images:

https://kit.svelte.dev/docs/link-options

I cloned the repo to stackblitz (thanks for that) and it doesn't show the error. The only change I made was adding styles.

https://stackblitz.com/edit/github-muzbyb?file=src/routes/+page.svelte

Those sveltekit examples are prior to 1.0, so need to be updated, but I probably won't have time until the weekend.

Another thing you can do is use bigger picture as a dynamic import with its own module. That way you can reuse the same instance everywhere in your app. I'll add it to the examples later, but it would work like this:

```ts
import type { BiggerPictureInstance } from 'bigger-picture'

let bp: BiggerPictureInstance

export async function loadBp() {
  if (!bp) {
    const { default: BiggerPicture } = await import('bigger-picture/svelte')
    bp = BiggerPicture({
      target: document.body,
    })
  }
  return bp
}
```

```ts
import { loadBp } from '...'

// use async function to load in onMount or event listener
let bp = await loadBp()
```

**Comment by germyparker** [comment]
>  I probably won't have time until the weekend.

No problem at all!  I was able to pull the guts out and use it without much trouble.

> This is definitely a sveltekit thing. You may be able to fix by disabling preload for those images:

This worked.  (If anyone else comes along, in my minimal repo, I added ```data-sveltekit-preload-data="off"``` to the wrapping container and the error disappeared.)

```
<section use:masonry data-sveltekit-preload-data="off">
``` 

> Another thing you can do is use bigger picture as a dynamic import with its own module. That way you can reuse the same instance everywhere in your app. I'll add it to the examples later, but it would work like this:

This sounds like the right approach, I'll try it once I get the 0.1 version working - I'm using accordions to hold image galleries (via carbon components), so there could be as many as 20 galleries, which I would prefer not to keep alive once its accordion is closed and another is open. Emptying the existing one and adding the new content seems like a good idea.

**Comment by henrygd** [comment]
I removed the older SvelteKit examples from the repo and added a dynamic import example on the latest version:

https://github.com/henrygd/bigger-picture-examples

Here's the demo of that app: https://sveltekit-dynamic-import.vercel.app/

I'm going to close this issue since we figured out the preload error, but please let me know if you have any more questions.
