### ISSUE TITLE
SvelteKit/SSR support

### ISSUE THREAD

**Issue by FluffyDiscord** [henrygd/bigger-picture#20]
Title

**Comment by henrygd** [comment]
It works with SvelteKit, you just need to make sure you're only running it in the browser context.

Here's a demo site: https://sveltekit-dynamic-import.vercel.app/

Here's a repo with the code for that demo: https://github.com/henrygd/bigger-picture-examples

I had to delete other examples that were from before SvelteKit 1.0, but I should be able to add more in the future.

I'd be happy to answer any other question you have in the [discussion thread](https://github.com/henrygd/bigger-picture/discussions/15). That way everything is collected in one place for anyone who needs it in the future.
