### ISSUE TITLE
Rollup warns of Unresolved dependencies

### ISSUE THREAD

**Issue by Buzut** [henrygd/bigger-picture#25]
Hey there,

Eventhough I npm i -S and double-checked everything, rollup can't seem to import the library when using ESM `import BiggerPicture from 'bigger-picture';`.

It used to work pretty well so far with your BigPicture library.
I'm using V2.33 so might have missed something?

**Comment by henrygd** [comment]
Hi, do you have a repo I can check out or a reproduction of the issue on stackblitz or codesandbox?

I tried a random rollup starter template and it works fine: https://stackblitz.com/edit/github-ba2mne?file=src/js/main.js

So I think it must be something specific to your project.
