### ISSUE TITLE
How to manipulate the current item of the initial gallery items while clicking a button inside a caption?

### ISSUE THREAD

**Issue by jovilog** [henrygd/bigger-picture#27]
Thanks for this awesome lightbox script.

I've managed to add a `button` to each caption and now I need to update the corresponding initial gallery item thumbnail (let's say add a class) when this button is clicked.

I tried `onUpdate(container, activeItem) { ... }`, used a click handler inside and then tried to manipulate `activeItem.element`. While this seemed to do the trick at first, I realized that when I've cycled through a couple of items in the lightbox (without clicking my custom buttons in their captions), then when I finally do click one of the buttons, `activeItem.element` manipulates ALL the initial items that I've cycled through so far, not just the current one.

How do I change only the one initial item corresponding to the current lightbox item?

I'll admit my JS is quite limited, an example would be great. Thank you very much in advance.

**Comment by henrygd** [comment]
Here's an example that works, if I'm understanding what you're trying to do. If not, let me know. 

https://codesandbox.io/s/bigger-picture-issue-27-9pu92i?file=/index.js

**Comment by jovilog** [comment]
Awesome, thank you so much.
My code probably lacked the `setTimeout` bit.

**Comment by henrygd** [comment]
No problem 👍
