### ISSUE TITLE
Svelte v5 

### ISSUE THREAD

**Issue by samaritanau** [henrygd/bigger-picture#38]
Hi, just upgraded to svelte 5 and get this warning when using your library (awesome work by the way thank you).

[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

**Comment by henrygd** [comment]
Should be gone in the next release. Just want to sort out the open pull request first.
