### ISSUE TITLE
undefined thumbnails generate 404s

### ISSUE THREAD

**Issue by ellemenno** [henrygd/bigger-picture#41]
if I don't define the `data-thumb` attribute, a fetch is still attempted on the undefined string value, resulting in a 404:

```
GET http://<my-site>/undefined 404 (Not Found)
```

in my use case, I am opening a gallery of images from a text link, so no thumbnail needed or wanted. but, to prevent the errors, I've needed to specify the attribute for every gallery item. I created a generic image that can be reused for all, but this is a lot of redundancy for something I don't think I need. Could one of the following be implemented instead?

1. (preferred) add a value check for `data-thumb`, and don't try to fetch when undefined
2. provide a global option to set a default value, so it doesn't need to be specified on every gallery item

everything else has been really smooth, thank you for providing this! it was simple to integrate, works well, and looks nice. also the css structure has made tweaking the caption and counter fonts easy to do.

**Comment by henrygd** [comment]
Glad it's working well for you. This should be fixed now in 1.1.14.
