### ISSUE TITLE
Is it possible to get the gallery example working without svelte?

### ISSUE THREAD

**Issue by dkern** [henrygd/bigger-picture#42]
Hi!

I would like to use this lightbox in a project. I need a thumbnail gallery there. The example on the website looks exactly like I need it.

https://codesandbox.io/p/sandbox/bigger-picture-thumbnails-vpszy7

But it seems to rely on svelte and some server-side packing if I see correct. Is there a way to get this done without?

Thanks for putting me in the right direction. ;)

**Comment by henrygd** [comment]
Sorry for the confusion.

That's not built into the library directly. You would need to recreate it on your own or add Svelte to your project to reuse the example code.

Please see #23 and #16 for more info / alternatives.
