### ISSUE TITLE
expose Svelte stores

### ISSUE THREAD

**Issue by warren-bank** [henrygd/bigger-picture#46]
Your [`BiggerPictureThumbnails` demo component](https://github.com/henrygd/bigger-picture/blob/v1.1.17/src/demo/bp-thumbnails.svelte) needs to import [`stores.js`](https://github.com/henrygd/bigger-picture/blob/v1.1.17/src/stores.js).

However, [`package.json`](https://github.com/henrygd/bigger-picture/blob/v1.1.17/package.json) prevents directly importing this file from the npm package.

My request is for the default export for _svelte_ to include an export for `stores`.

Specifically:

* in file: [`src/bigger-picture.js`](https://github.com/henrygd/bigger-picture/blob/v1.1.17/src/bigger-picture.js)
* add the line:
  ```js
    export * as stores from './stores.js'
  ```

...which would allow a user to create a custom component (such as `BiggerPictureThumbnails`) with the import:
```js
  import {stores} from 'bigger-picture/svelte'
```

**Comment by henrygd** [comment]
I added a way to import it in the `@next` release and will be included in full releases going forward. That file is internal stuff so I'm not going to add it to the docs and can't promise that it won't be modified in the future. It's unlikely to be though.

```sh
pnpm install bigger-picture@next
```

```ts
import { prefersReducedMotion, closing } from 'bigger-picture/svelte/stores'

console.log('prefersReducedMotion', prefersReducedMotion)

closing.subscribe((bool) => {
    console.log('gallery is closing', bool)
})
```

Let me know if that doesn't work for you. It does require svelte to be installed.

**Comment by warren-bank** [comment]
Looks good to me. Thanks :smiley:
